name: sensors_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  permission_handler: ^12.0.1
  sensors_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
