name: sensors_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  quick_actions: ^1.1.0
  sensors_plus: ^6.1.2
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community_generator: ^3.3.0-dev.2
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
